apiVersion: v1
kind: Service
metadata:
  name: deploy-react-kubernetes-service
  labels:
    app: app
spec:
  # type: NodePort
  type: LoadBalancer
  ports:
  - port: 80
    # name: http
    name: deploy-react-kubernetes
    # nodePort: 30080
    targetPort: 3000
  selector:
    app: app
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deploy-react-kubernetes-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: deploy-react-kubernetes
          # image: registry.<ibm_cloud_region>.bluemix.net/<your_namespace>/deploy-react-kubernetes
          image: ${ORIGIN_REPO}/${REPO}:${IMAGE_TAG2}
          PullPolicy: Always
          ports:
            - containerPort: 3000
      # restartPolicy: Always
